# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@stable'
    'frameworks/ki18n': '@stable'
    'frameworks/kdoctools': '@stable'
    'frameworks/kio': '@stable'
    'frameworks/purpose': '@stable'
    'network/kaccounts-integration': '@same'
    'pim/libkgapi': '@same'

Options:
  require-passing-tests-on: [ 'Linux', 'FreeBSD' ]
