# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
 - 'on': ['Linux/Qt6', 'FreeBSD/Qt6']
   'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/ki18n': '@latest-kf6'
    'frameworks/kdoctools': '@latest-kf6'
    'frameworks/kio': '@latest-kf6'
    'frameworks/purpose': '@latest-kf6'
    'pim/libkgapi': '@latest-kf6'
    'network/kaccounts-integration': '@latest-kf6'
    'third-party/qtkeychain': '@latest'

Options:
 require-passing-tests-on: ['Linux', 'FreeBSD']
